apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
  namespace: python-app
  labels:
    app: python-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - python-app.example.com
    secretName: python-app-tls
  rules:
  - host: python-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-app
            port:
              number: 80
