apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: python-app
  labels:
    app: python-app
  annotations:
    description: "Service for Python Flask Application"
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
